### PR TITLE
Repeat 'venv' creation in publish job 

### PR DESCRIPTION
**Pull request by ephraimbuddy**
The restoring of virtualenv doesn't work in this alpine image in publish job

### CODE REVIEW

**Comment by ephraimbuddy** [comment]
> Through a series of symlinks, the Python3 executable from `.venv` is pointing at a nonexistent virtualenv created by PyEnv.
> 
> Removing the save to/restore from cache for the `.venv` directory might help get us a fresh virtualenv each time. With as few dependencies as this project seems to have, I'm not sure that the time saved via caching is worth the effort of debugging and maintaining it.

I added the verify step as a separate job. I think that's better. The publish step has to depend on the verify step.

**Comment by ashb** [comment]
I don't understand why this change is needed?

From a workflow point of view, verifying the tag is a step in publishing, not a whole separate job though.

**Comment by ephraimbuddy** [comment]
> I don't understand why this change is needed?
> 
> From a workflow point of view, verifying the tag is a step in publishing, not a whole separate job though.

Ok. I will go back to the publish step. The issue was that I and @Drew have tried several things on the publish step container. The restored virtualenv doesn't work and installing a new environment also gives issues.

**Comment by ephraimbuddy** [comment]
This worked in my test

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
